### ISSUE TITLE
Cant deal with empty/undefined type.

### ISSUE THREAD

**Issue by Inrixia** [thejonwithnoh/nbt-js#1]
I'm trying to parse this nbt file:
[02f8abf5-8d2f-4a68-962e-0741ba1af5aa.zip](https://github.com/thejonwithnoh/nbt-js/files/1546541/02f8abf5-8d2f-4a68-962e-0741ba1af5aa.zip)

Its weird because I can run it on other files that have a similar structure and it dosn't break....

I have been fiddling a bit trying to fix it myself but I don't quite understand how your dealing with the data, though I feel it should be a relatively easy fix. 

[![https://gyazo.com/f12a15d06ee99c9e494cfa8ffb8806f3](https://i.gyazo.com/f12a15d06ee99c9e494cfa8ffb8806f3.png)](https://gyazo.com/f12a15d06ee99c9e494cfa8ffb8806f3)

**Comment by Inrixia** [comment]
Found out some more info... It appears to be not reading the first bit of the file correctly for some reason?

As you can see its printing out urtby... as the key instead of HurtyBy which is the first key of the file...

[![https://gyazo.com/85ba87bb2b9f4a8c96bd218cf8c66263](https://i.gyazo.com/85ba87bb2b9f4a8c96bd218cf8c66263.png)](https://gyazo.com/85ba87bb2b9f4a8c96bd218cf8c66263)
[![https://gyazo.com/c7efb4c20e2465a14f8dbb0bb4da59c6](https://i.gyazo.com/c7efb4c20e2465a14f8dbb0bb4da59c6.png)](https://gyazo.com/c7efb4c20e2465a14f8dbb0bb4da59c6)

Dunno if its helps or not:/

**Comment by thejonwithnoh** [comment]
When I download your zip file, extract it, and then run the resulting file through the sample code I have in the readme, it seems to work with no problems.  Would you be able to provide more details which might help narrow down the issue?  Perhaps show some of the code you're using in your serverAPI.js file?

To be clear, when I run the following code:

```javascript
var fs    = require('fs');
var zlib  = require('zlib');
var nbt   = require('nbt-js');

var file  = fs.readFileSync('02f8abf5-8d2f-4a68-962e-0741ba1af5aa.dat'); // changed file name here
var level = zlib.gunzipSync(file);
var tag   = nbt.read(level);

console.log(JSON.stringify(tag.payload, null, 4)); // modified to format output
```

It prints the following (which I've of course shortened):

```javascript
{
    "": {
        "Spawns": [],
        "TConstruct": {
            "derpLevel": 1,
            "Knapsack": [],
            "smelteryManual": 1,
            "weaponryManual": 1,
            "beginnerManual": 1,
            "materialManual": 1,
            "battlesignBonus": 1,
            "Inventory": [
                {
                    "Slot": 6,
                    "id": 4893,
                    "Count": 10,
                    "Damage": 2
                }
            ]
        },
        "SleepTimer": 0,
        "SpawnForced": 0,

        // remove remaining items for brevity

    }
}
```

**Comment by Inrixia** [comment]
Ah! I figured out whats causing it... I wasn't doing zlib.gunzipSync(file); as some other nbt files worked without it. Such a simple mistake on my part :)

Just gotta make sure to zlib.gunzipSync(file) the file. Thanks for the help <3

**Comment by thejonwithnoh** [comment]
No problem, glad I could help :-)
